# Link the C runtime statically so installed binaries do not depend on the
# Visual C++ redistributable being present on the target machine.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
